import type { Channel, ChannelModel, ConfirmChannel, ConsumeMessage } from 'amqplib';
import { propagation, context, type Tracer } from '@opentelemetry/api';
import type { IContainer, ILogger, IMessage, IMessageMeta } from '../interfaces/index.ts';
import * as Event from '../Event.ts';
import { recordSpanError, spanAttributes, spanContext } from '../telemetry/index.ts';
import { assertFunction, assertMessage, assertString, extractErrorDetails, Lock } from '../utils/index.ts';
import { registerExitCleanup } from './utils/index.ts';
import { EventEmitter } from 'events';

/** Generate a short pseudo-unique identifier using a truncated timestamp and random component */
const getRandomAppId = () =>
	`${Date.now().toString(36).slice(-4)}.${Math.random().toString(36).slice(2, 6)}`.toUpperCase();

type MessageHandler = (m: IMessage, meta?: IMessageMeta) => Promise<unknown> | unknown;

/**
 * Represents a subscription to events from a RabbitMQ exchange.
 */
type Subscription = {

	/** Name of the exchange to subscribe to */
	exchange: string;

	/** Optional durable queue name; if omitted, an exclusive temporary queue is used */
	queueName?: string;

	/** Specific event type (routing key) for filtering, defaults to all if omitted */
	eventType?: string;

	/** Callback function to process received messages */
	handler: MessageHandler;

	/** If true, messages originating from this instance are ignored */
	ignoreOwn?: boolean;

	/** Optional limit for concurrent message handling */
	concurrentLimit?: number;

	/**
	 * If true, the broker won't expect an acknowledgement of messages delivered to this consumer;
	 * i.e., it will dequeue messages as soon as they've been sent down the wire.
	 *
	 * Defaults to `false` - messages are acknowledged after successful handler completion or rejected on exception.
	 */
	noAck?: boolean;

	/**
	 * Handler timeout in milliseconds; if the handler does not complete within this time,
	 * the message is considered failed and is rejected.
	 *
	 * Defaults to 1h (`RabbitMqGateway.HANDLER_PROCESS_TIMEOUT`)
	 */
	handlerProcessTimeout?: number;
};

type EstablishedSubscription = Subscription & {

	/**
	 * Either a durable queue name or an autogenerated exclusive queue name.
	 *
	 * Stays empty until a queue is asserted and a subscription is set up successfully.
	 */
	queueGivenName?: string;
}

const isSystemQueue = (queueName: string) => queueName.startsWith('amq.');

const describeSub = (s: EstablishedSubscription) =>
	`to${s.queueName ?? s.queueGivenName ? ` queue "${s.queueName ?? s.queueGivenName}" of` : ''} exchange "${s.exchange}"`;

const extractMessageMeta = (msg: ConsumeMessage) => ({
	consumerTag: msg.fields?.consumerTag,
	routingKey: msg.fields?.routingKey,
	messageId: msg.properties?.messageId,
	correlationId: msg.properties?.correlationId,
	appId: msg.properties?.appId
});

interface RabbitMqGatewayConnected {
	get connection(): ChannelModel;
}

type GatewayEvents = {
	connected: [];
	disconnected: [reason?: string];
};

/**
 * RabbitMqGateway provides RabbitMQ-based publish/subscribe for ICommand/IEvent-style messages.
 *
 * It uses a fanout exchange to broadcast messages to all connected subscribers.
 * The `on` and `off` methods allow you to register and remove handlers for specific event types.
 * The `queue(name)` method creates or returns a durable queue with the given name, ensuring that
 * all messages delivered to the fanout exchange are also routed to this queue.
 */
export class RabbitMqGateway {

	static HANDLER_PROCESS_TIMEOUT = 60 * 60 * 1000; // 1 hour
	static ALL_EVENTS_WILDCARD = '*';
	static RECONNECT_DELAY = 30_000; // 30 sec

	readonly #connectionFactory: () => Promise<ChannelModel>;
	readonly #appId: string;
	readonly #logger: ILogger | undefined;
	readonly #emitter: EventEmitter<GatewayEvents>;
	readonly #tracer: Tracer | undefined;

	#desiredState: 'connected' | 'disconnected' = 'disconnected';
	#stateChangeLock = new Lock();

	/**
	 * Established connection to RabbitMQ.
	 * If empty, the gateway is not connected.
	 */
	#connection: ChannelModel | undefined;
	#pubChannel: ConfirmChannel | undefined;
	#exclusiveQueueName: string | undefined;
	#queueChannels = new Map<string, Channel>();
	#queueConsumers = new Map<string, { channel: Channel, consumerTag: string }>();

	#subscriptions: Array<EstablishedSubscription> = [];

	get connection(): ChannelModel | undefined {
		return this.#connection;
	}

	isConnected(): this is this & RabbitMqGatewayConnected {
		return !!this.#connection;
	}

	constructor(o: Partial<Pick<IContainer, 'logger' | 'process' | 'tracerFactory'>> & {
		rabbitMqConnectionFactory?: () => Promise<ChannelModel>,
		eventEmitterFactory?: () => EventEmitter<GatewayEvents>
	}) {
		assertFunction(o?.rabbitMqConnectionFactory, 'o.rabbitMqConnectionFactory');

		this.#emitter = o?.eventEmitterFactory?.() ?? new EventEmitter();
		this.#connectionFactory = o.rabbitMqConnectionFactory;
		this.#appId = getRandomAppId();
		this.#tracer = o?.tracerFactory?.(new.target.name);
		this.#logger = o.logger && 'child' in o.logger ?
			o.logger.child({ service: new.target.name, appId: this.#appId }) :
			o.logger;

		registerExitCleanup(o.process, () => this.disconnect());
	}

	/**
	 * Establishes a connection to RabbitMQ.
	 * If a connection attempt is already in progress, it waits for it to complete.
	 * If the connection is lost, it attempts to reconnect automatically.
	 * Upon successful connection, it restores any previously active subscriptions.
	 *
	 * This method is called automatically by other methods if a connection is required but not yet established.
	 *
	 * @returns A promise that resolves with the ChannelModel representing the established connection.
	 */
	async connect(): Promise<ChannelModel> {
		this.#desiredState = 'connected';
		this.#clearReconnectTimer();

		const lease = await this.#stateChangeLock.acquire();
		try {
			if (this.#connection) {
				this.#logger?.debug('Connection is already established');
				return this.#connection;
			}

			return await this.#connect();
		}
		finally {
			lease.release();
		}
	}

	async #connect(): Promise<ChannelModel> {
		try {
			const connection = await this.#connectionFactory();
			connection.on('error', err => this.#onConnectionError(err));
			connection.on('close', () => this.#onConnectionClosed(connection));

			this.#connection = connection;

			this.#logger?.info('Connection established');

			await this.#restoreSubscriptions();

			this.#emitter.emit('connected');

			return this.#connection;
		}
		catch (err: unknown) {
			this.#logger?.error('Connection attempt failed', {
				error: extractErrorDetails(err)
			});

			if (this.#desiredState === 'connected')
				this.#scheduleReconnect();

			throw err;
		}
	}

	#reconnectTimeout: NodeJS.Timeout | undefined;

	#clearReconnectTimer() {
		if (!this.#reconnectTimeout)
			return;

		clearTimeout(this.#reconnectTimeout);
		this.#reconnectTimeout = undefined;
	}

	#scheduleReconnect() {
		if (this.#desiredState !== 'connected')
			return;

		this.#clearReconnectTimer();

		this.#logger?.debug(`Scheduling reconnect in ${RabbitMqGateway.RECONNECT_DELAY / 1000} seconds`);
		this.#reconnectTimeout = setTimeout(() => this.#reconnect(), RabbitMqGateway.RECONNECT_DELAY).unref();
	}

	#reconnect() {
		if (this.#desiredState !== 'connected' || this.isConnected())
			return;

		this.connect().catch(() => undefined);
	}

	async #restoreSubscriptions() {
		for (let i = 0; i < this.#subscriptions.length; i++) {
			const subscriptionToRestore = this.#subscriptions.shift();
			if (!subscriptionToRestore) // should never happen; check is for type consistency
				continue;

			await this.#subscribe(subscriptionToRestore);
		}

		this.#logger?.debug(`${this.#subscriptions.length} subscription(s) restored`);
	}

	async disconnect() {
		this.#desiredState = 'disconnected';
		this.#clearReconnectTimer();

		const lease = await this.#stateChangeLock.acquire();

		try {
			if (!this.#connection) {
				this.#logger?.debug('Connection is not established');
				return;
			}

			this.#logger?.debug('Disconnecting from RabbitMQ...');

			await this.#stopConsuming();
			await this.#connection.close();

			if (this.#connection) // clean up in case 'close' event was not triggered
				this.#cleanup();

			this.#logger?.debug('Disconnected from RabbitMQ');
			this.#emitter.emit('disconnected', 'Disconnected by request');
		}
		catch (err: unknown) {
			this.#logger?.error('Failed to disconnect from RabbitMQ', {
				error: extractErrorDetails(err)
			});
		}
		finally {
			lease.release();
		}
	}

	async #stopConsuming() {
		this.#logger?.debug('Stopping all consumers...');

		const cancellations = [...this.#queueConsumers.entries()].map(async ([queueName, { channel, consumerTag }]) => {
			this.#logger?.debug(`Cancelling consumer "${consumerTag}" for queue "${queueName}"`);
			try {
				await channel.cancel(consumerTag);
				this.#logger?.debug(`Consumer "${consumerTag}" on queue "${queueName}" cancelled successfully`);
				this.#queueConsumers.delete(queueName);
			}
			catch (err: unknown) {
				this.#logger?.error(`Failed to cancel consumer "${consumerTag}" for queue "${queueName}"`, {
					error: extractErrorDetails(err)
				});
			}
		});

		await Promise.all(cancellations);
		this.#logger?.info('All consumers stopped');
	}

	#onConnectionError(err: unknown) {
		this.#logger?.error('Connection error', {
			error: extractErrorDetails(err)
		});
	}

	#onConnectionClosed(connection: ChannelModel) {
		if (connection !== this.#connection)
			return;

		this.#logger?.info('Connection closed');
		this.#cleanup();

		if (this.#desiredState === 'connected') {
			this.#emitter.emit('disconnected', 'Connection closed');
			this.#reconnect();
		}
	}

	#cleanup() {
		this.#connection = undefined;
		this.#pubChannel = undefined;
		this.#exclusiveQueueName = undefined;
		this.#queueChannels.clear();
		this.#queueConsumers.clear();
	}

	#getHandlers(queueGivenName: string = '', eventType: string = RabbitMqGateway.ALL_EVENTS_WILDCARD) {
		return this.#subscriptions.filter(s =>
			s.queueGivenName === queueGivenName
			&& (
				!s.eventType
				|| s.eventType === RabbitMqGateway.ALL_EVENTS_WILDCARD
				|| s.eventType === eventType
			)
		);
	}

	async subscribeToQueue(exchange: string, queueName: string, handler: MessageHandler,
		options?: Omit<Subscription, 'exchange' | 'queueName' | 'handler'>) {
		return this.subscribe({ exchange, queueName, handler, ...options });
	}

	/**
	 * Subscribes to a non-durable, exclusive queue without requiring acknowledgments.
	 * The queue is deleted when the connection closes.
	 * Messages are considered "delivered" upon receipt.
	 * Failed message processing does not result in redelivery or dead-lettering.
	 */
	async subscribeToFanout(exchange: string, handler: MessageHandler,
		options?: Omit<Subscription, 'exchange' | 'handler'>) {
		return this.subscribe({ exchange, handler, ignoreOwn: true, ...options });
	}

	/**
	 * Subscribes to events from a specified exchange.
	 *
	 * This method sets up the necessary RabbitMQ topology (exchange, queue, bindings) based on the provided details.
	 * If a `queueName` is provided, it asserts a durable queue with a dead-letter queue for failed messages.
	 * If `queueName` is omitted, it uses or creates a temporary, exclusive queue for the connection.
	 * Then it starts consuming messages from the queue with the specified concurrency limit, if specified.
	 *
	 * @param subscription - The subscription details.
	 * @param subscription.exchange - The name of the exchange to subscribe to.
	 * @param subscription.queueName - Optional. The name of the durable queue. If omitted, an exclusive queue is used.
	 * @param subscription.eventType - The routing key or pattern to bind the queue with.
	 * @param subscription.concurrentLimit - Optional. The maximum number of concurrent messages to process.
	 * @returns A promise that resolves when the subscription is successfully set up.
	 */
	async subscribe(subscription: Subscription) {
		this.#desiredState = 'connected';
		this.#clearReconnectTimer();

		const lease = await this.#stateChangeLock.acquire();
		try {
			if (!this.#connection)
				await this.#connect();

			await this.#subscribe(subscription);
		}
		finally {
			lease.release();
		}
	}

	async #subscribe(subscription: Subscription) {
		const subscriptionExists = !!this.#findSubscription(subscription);
		if (subscriptionExists)
			throw new Error(`Subscription ${describeSub(subscription)} already exists`);

		// record subscription details to restore it if connection attempt fails or on reconnect
		this.#subscriptions.push(subscription);
		this.#logger?.debug(`Subscription ${describeSub(subscription)} recorded`);

		const {
			exchange,
			queueName,
			eventType
		} = subscription;

		const channel = await this.#assertQueueChannel(queueName);

		let queueGivenName = queueName;
		if (!queueGivenName) {
			// Handle temporary (exclusive) queue case
			if (!this.#exclusiveQueueName) {
				// Assert temporary "exclusive" queue that will be destroyed on connection termination
				this.#exclusiveQueueName = await this.#assetQueue(channel, exchange, '', eventType, {
					exclusive: true,
					durable: false
				});
			}
			else {
				// If exclusive queue already exists, ensure it is bound with the current event type
				await this.#assertBinding(channel, exchange, this.#exclusiveQueueName, eventType);
			}
			queueGivenName = this.#exclusiveQueueName;
		}
		else {
			// Handle durable queue case
			const deadLetterExchangeName = `${exchange}.failed`;

			// Assert dead letter queue for rejected or timed out messages
			await this.#assetQueue(channel, deadLetterExchangeName, `${queueGivenName}.failed`);

			// Assert durable queue that will survive broker restart
			await this.#assetQueue(channel, exchange, queueGivenName, eventType, { deadLetterExchangeName });
		}

		const subscriptionRecord = this.#findSubscription(subscription);
		if (subscriptionRecord)
			subscriptionRecord.queueGivenName = queueGivenName;

		await this.#assertConsumer(queueGivenName, channel, subscription);

		this.#logger?.debug(`Subscription ${describeSub(subscription)} established`);
	}

	#findSubscription(subscription: Pick<Subscription, 'exchange' | 'queueName' | 'eventType' | 'handler'>) {
		return this.#subscriptions.find(s =>
			s.exchange === subscription.exchange &&
			s.queueName === subscription.queueName &&
			s.eventType === subscription.eventType &&
			s.handler === subscription.handler);
	}

	async unsubscribe(subscription: Pick<Subscription, 'exchange' | 'queueName' | 'eventType' | 'handler'>) {
		const subscriptionToRemove = this.#findSubscription(subscription);
		if (!subscriptionToRemove)
			throw new Error('Such subscription does not exist');

		this.#subscriptions = this.#subscriptions.filter(s => s !== subscriptionToRemove);

		await this.#tryDropConsumer(subscriptionToRemove);

		this.#logger?.debug(`Subscription ${describeSub(subscriptionToRemove)} removed`);
	}

	async #assertConnection() {
		return this.#connection ?? this.connect();
	}

	/** Get existing or open a new channel for a given queue name */
	async #assertQueueChannel(queueName: string = ''): Promise<Channel> {
		let channel = this.#queueChannels.get(queueName);
		if (!channel) {
			if (!this.#connection)
				throw new Error('No connection established to create channel');

			channel = await this.#connection.createChannel();
			this.#queueChannels.set(queueName, channel);
		}
		return channel;
	}

	/**
	 * Ensure queue, exchange, and binding exist
	 */
	async #assetQueue(channel: Channel, exchange: string, queueName: string, eventType?: string, options?: {

		/** The queue will survive a broker restart */
		durable?: boolean,

		/** Used by only one connection and the queue will be deleted when that connection closes */
		exclusive?: boolean,

		/** Exchange where rejected or timed out messages will be delivered */
		deadLetterExchangeName?: string,
	}) {
		const {
			durable = true,
			exclusive = false,
			deadLetterExchangeName
		} = options ?? {};

		await channel.assertExchange(exchange, 'topic', { durable: true });
		const { queue: queueGivenName } = await channel.assertQueue(queueName, {
			exclusive,
			durable,
			arguments: {
				...deadLetterExchangeName && {
					'x-dead-letter-exchange': deadLetterExchangeName
				},
				...durable && {
					// Use quorum queues (Raft-replicated, HA alternative to classic queues) for durable workloads
					'x-queue-type': 'quorum'
				}
			}
		});

		await this.#assertBinding(channel, exchange, queueGivenName, eventType);

		return queueGivenName;
	}

	async #assertBinding(channel: Channel, exchange: string, queueGivenName: string, eventType?: string) {
		if (!eventType || eventType === RabbitMqGateway.ALL_EVENTS_WILDCARD)
			eventType = '#';

		await channel.bindQueue(queueGivenName, exchange, eventType);

		this.#logger?.debug(`Queue "${queueGivenName}" bound to exchange "${exchange}" with pattern "${eventType}"`);
	}

	async #assertConsumer(
		queueGivenName: string,
		channel: Channel,
		options?: Pick<Subscription, 'concurrentLimit' | 'noAck' | 'handlerProcessTimeout'>
	) {
		if (this.#queueConsumers.has(queueGivenName))
			return;

		if (options?.concurrentLimit !== undefined)
			await channel.prefetch(options.concurrentLimit);

		const c = await channel.consume(queueGivenName, async (msg: ConsumeMessage | null) => {
			if (!msg)
				return;

			// Keep the process alive while waiting for the handler to finish
			const handlerProcessTimeout = options?.handlerProcessTimeout ?? RabbitMqGateway.HANDLER_PROCESS_TIMEOUT;
			const keepAliveTimeout = setTimeout(() => {
				this.#logger?.error('Message processing timed out', {
					queueName: queueGivenName,
					msg: extractMessageMeta(msg)
				});
				this.#rejectMessage(channel, msg);
			}, handlerProcessTimeout);

			try {
				this.#logger?.debug('Message received', {
					queueName: queueGivenName,
					msg: extractMessageMeta(msg)
				});

				const jsonContent = msg.content.toString();
				const message: IMessage = JSON.parse(jsonContent);

				// Extract OTel trace context from AMQP headers to continue the distributed trace
				const parentContext = propagation.extract(context.active(), msg.properties?.headers ?? {});
				const span = this.#tracer?.startSpan(
					`RabbitMqGateway.consume ${message.type}`,
					spanAttributes('rabbitmq', message, ['type', 'aggregateId']),
					parentContext
				);

				try {
					const handlers = this.#getHandlers(queueGivenName, message.type);
					if (!handlers.length && !isSystemQueue(queueGivenName))
						throw new Error(`Message from queue "${queueGivenName}" was delivered to a consumer that does not handle type "${message.type}"`);

					for (const { handler, ignoreOwn } of handlers) {
						if (ignoreOwn && msg.properties.appId === this.#appId)
							continue;

						await handler(message, { span });
					}

					channel.ack(msg);
				}
				catch (err: unknown) {
					recordSpanError(span, err);
					throw err;
				}
				finally {
					span?.end();
				}
			}
			catch (err: unknown) {
				this.#logger?.error('Message processing failed', {
					error: extractErrorDetails(err),
					queueName: queueGivenName,
					msg: extractMessageMeta(msg)
				});

				this.#rejectMessage(channel, msg);
			}
			finally {
				clearTimeout(keepAliveTimeout);
			}
		}, {
			noAck: options?.noAck
		});

		this.#logger?.debug(`Consumer "${c.consumerTag}" registered on queue "${queueGivenName}"`);

		this.#queueConsumers.set(queueGivenName, {
			channel,
			consumerTag: c.consumerTag
		});
	}

	/** Reject a message, causing it to be dead-lettered or discarded */
	#rejectMessage(channel: Channel, msg: ConsumeMessage) {
		try {
			channel.nack(msg, false, false);
		}
		catch (err: unknown) {
			this.#logger?.warn('Failed to reject message', {
				error: extractErrorDetails(err),
				msg: extractMessageMeta(msg)
			});
		}
	}

	async #tryDropConsumer(subscription: EstablishedSubscription) {
		if (!subscription.queueGivenName) {
			this.#logger?.warn(`Subscription ${describeSub(subscription)} is not bound to a queue`);
			return;
		}
		const queueStillUsed = this.#subscriptions.some(s => s.queueGivenName === subscription.queueGivenName);
		if (queueStillUsed) {
			this.#logger?.warn(`Queue "${subscription.queueGivenName}" has other consumers in this process`);
			return;
		}

		const consumer = this.#queueConsumers.get(subscription.queueGivenName);
		if (!consumer) {
			this.#logger?.warn(`Queue "${subscription.queueGivenName}" does not have consumers`);
			return;
		}

		this.#queueConsumers.delete(subscription.queueGivenName);
		await consumer.channel.cancel(consumer.consumerTag);

		this.#logger?.info(`Consumer "${consumer.consumerTag}" removed from subscription ${describeSub(subscription)}`);
	}

	/**
	 * Publishes an event to the fanout exchange.
	 * The event will be delivered to all subscribers, except this instance's own consumer.
	 */
	async publish(exchange: string, message: IMessage, meta?: IMessageMeta): Promise<void> {
		assertString(exchange, 'exchange');
		assertMessage(message, 'message');

		const span = this.#tracer?.startSpan(`RabbitMqGateway.publish ${message.type}`,
			spanAttributes('rabbitmq', message, ['type', 'aggregateId']),
			spanContext(meta)
		);

		try {
			if (!this.#pubChannel) {
				const connection = await this.#assertConnection();
				this.#pubChannel = await connection.createConfirmChannel();

				await this.#pubChannel.assertExchange(exchange, 'topic', { durable: true });
			}

			const content = Buffer.from(JSON.stringify(message), 'utf8');
			const sagaCorrelationId = (() => {
				const sagaOrigins = message.sagaOrigins;
				if (!sagaOrigins || typeof sagaOrigins !== 'object')
					return undefined;

				const sagaDescriptors = Object.keys(sagaOrigins);
				if (sagaDescriptors.length !== 1)
					return undefined;

				return sagaOrigins[sagaDescriptors[0]];
			})();

			// Inject OTel trace context into AMQP headers so consumers can continue the trace
			const headers: Record<string, string> = {};
			const parentContext = span ?
				spanContext({ span }) :
				spanContext(meta);
			propagation.inject(parentContext, headers);

			const properties = {
				contentType: 'application/json',
				contentEncoding: 'utf8',
				persistent: true,
				timestamp: message.context?.ts ?? Date.now(),
				appId: this.#appId,
				type: message.type,
				messageId: 'id' in message && typeof message.id === 'string' ?
					message.id :
					undefined,
				correlationId: sagaCorrelationId,
				headers
			};

			return await new Promise<void>((resolve, reject) => {
				if (!this.#pubChannel)
					throw new Error('No channel available for publishing');

				this.#logger?.debug(`Publishing message "${Event.describe(message)}" to exchange "${exchange}"`);

				const published = this.#pubChannel.publish(exchange, message.type, content, properties, err =>
					(err ? reject(err) : resolve()));
				if (!published)
					throw new Error(`Failed to send event ${Event.describe(message)}, channel buffer is full`);
			});
		}
		catch (error: unknown) {
			recordSpanError(span, error);
			throw error;
		}
		finally {
			span?.end();
		}
	}

	on<K extends keyof GatewayEvents>(event: K, fn: (...args: GatewayEvents[K]) => void) {
		this.#emitter.on<K>(event, fn as any);
		return this;
	}

	once<K extends keyof GatewayEvents>(event: K, fn: (...args: GatewayEvents[K]) => void) {
		this.#emitter.once<K>(event, fn as any);
		return this;
	}

	off<K extends keyof GatewayEvents>(event: K, fn: (...args: GatewayEvents[K]) => void) {
		this.#emitter.off<K>(event, fn as any);
		return this;
	}
}
