name: Audit

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '0 8 * * 1' # Mondays at 08:00 UTC
  workflow_call: # required to pass before publishing, see publish.yml

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7.0.1
    - name: Use Node.js 24.x
      uses: actions/setup-node@v7.0.0
      with:
        node-version: 24.x
    - run: npm audit --parseable --omit=dev --audit-level=moderate
