name: Coverage

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  coveralls:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7.0.1
    - name: Use Node.js 24.x
      uses: actions/setup-node@v7.0.0
      with:
        node-version: 24.x
    - run: npm ci
      env:
        CI: true
    - run: npm run test:coverage
    - name: Submit to Coveralls
      uses: coverallsapp/github-action@v2.3.8
