name: Lint

on:
  push:
    branches:
      - master
  pull_request:
  workflow_call: # required to pass before publishing, see publish.yml

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7.0.1
    - name: Use Node.js 24.x
      uses: actions/setup-node@v7.0.0
      with:
        node-version: 24.x
    - run: npm ci
      env:
        CI: true
    - run: npm run lint
